# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQwJ4AF68CCBIQoD3xQW83jw6odjcGy_
"""

from setuptools import setup, find_packages

setup(
    name='turboguard',
    version='2.0.0',
    packages=find_packages(where="src"),
    package_dir={'': 'src'},
    include_package_data=True,
    install_requires=[],
)